language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
before_script:
    - sudo apt-get install cabal-install
    - cabal update
    - cabal install pandoc
    - export PATH=~/.cabal/bin:$PATH
script:
    - python setup.py develop test
